large_flask_app/myproject/models.py
#set up the db inside __init__.py under myproject folder
from myproject import db
class Puppy(db.Model):
    __tablename__='puppies'
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.Text)
    owner=db.relationship("Owner",backref='Puppy',uselist=False)#one to one realtion, puppy to owner
    def __init__(self,name):
        self.name=name
    def __repr__(self):
        if self.owner:
            return f"puppy name is {self.name} and owner is {self.owner.name}"
        else:
            return f"Puppy name is {self.name} and has no owner yet"

class Owner(db.Model):
    __tablename__='owners'
    id = db.Column(db.Integer,primary_key=True)
    name=db.Column(db.Text)
    puppy_id=db.Column(db.Integer,db.ForeignKey('puppies.id'))
    def __init__(self,name,puppy_id):
        self.name=name
        self.puppy_id=puppy_id
    def __repr__(self):
        return f"owner name is : {self.name}"

large_flask_app/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField,StringField,SubmitField

class AddForm(FlaskForm):
    name = StringField("Name Of owner")
    pup_id=IntegerField("Id Of Puppy")
    submit=SubmitField('Add Owner')

large_flask_app/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField,StringField,SubmitField

class AddForm(FlaskForm):
    name=StringField('puppy name')
    submit=SubmitField("Add Puppy")

class DelForm(FlaskForm):
    id = IntegerField("please enter id of puppy which means delete")
    submit=SubmitField('Del Puppy')

large_flask_app/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

basedir=os.path.abspath(os.path.dirname(__file__))

app=Flask(__name__)

app.config['SECRET_KEY']='mysecretkey'
app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

db=SQLAlchemy(app)
Migrate(app,db)

from myproject.puppies.views import puppies_blueprints
from myproject.owners.views import owners_blueprints

app.register_blueprint(owners_blueprints,url_prefix='/owners')
app.register_blueprint(puppies_blueprints,url_prefix='/puppies')

large_flask_app/myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprints=Blueprint("owners",__name__,template_folder="templates/owners")

@owners_blueprints.route('/add',methods=['GET','POST'])
def add():
    form=AddForm()
    if form.validate_on_submit():
        name=form.name.data
        pup_id=form.pup_id.data
        new_owner=Owner(name,pup_id)
        db.session.add(new_owner)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template("add_owner.html",form=form)

large_flask_app/myproject/puppies/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm,DelForm

puppies_blueprints=Blueprint("puppies",__name__,template_folder="templates/puppies")

@puppies_blueprints.route('/add',methods=['GET','POST'])
def add():
    form=AddForm()
    if form.validate_on_submit():
        name=form.name.data
        new_pup=Puppy(name)
        db.session.add(new_pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template("add.html",form=form)

@puppies_blueprints.route('/list')
def list():
    puppies=Puppy.query.all()
    return render_template('list.html',puppies=puppies)

@puppies_blueprints.route('/delete',methods=['GET','POST'])
def delete():
    form=DelForm()
    if form.validate_on_submit():
        id=form.name.data
        pup=Puppy.query.get(id)
        db.session.delete(pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template("delete.html",form=form)

large_flask_app/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Flask Object relational mapper</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-item nav-link" href="{{url_for('index')}}">home</a>
    <a class="navbar-item nav-link" href="{{url_for('puppies.add')}}">add_pup</a>
    <a class="navbar-item nav-link" href="{{url_for('puppies.list')}}">list_pup</a>
    <a class="navbar-item nav-link" href="{{url_for('puppies.delete')}}">delete_pup</a>
    <a class="navbar-item nav-link" href="{{url_for('owners.add')}}">Add Owner</a>
        </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

large_flask_app/myproject/templates/home.html
{% extends 'base.html'%}
{% block content %}
<div class="jumbotron">
<h1>Welcome adoption page</h1>
<p>please select the link from the navbar</p>
</div>
{% endblock %}